In [ ]:
# एक 5x5 मैट्रिक्स बनाओ जिसमें 1 से 25 तक के नंबर भरे हों। फिर: diagonal elements (main + secondary दोनों) निकालो। दोनों diagonals का sum निकालो।

In [18]:
import numpy as np
import random
a=np.random.randint(1,26,(5,5))
a

array([[ 1, 16, 17, 22, 10],
       [11,  1, 25,  2, 16],
       [ 6, 13,  6, 19, 10],
       [18,  2, 15,  2,  8],
       [14, 13,  4, 24, 11]], dtype=int32)

In [19]:
d=np.diag(a).sum()
d

np.int64(21)

In [20]:
flip=np.diag(np.fliplr(a)).sum()

In [21]:
flip

np.int64(34)

In [22]:
d+flip

np.int64(55)

In [23]:
# एक 10x10 random integer matrix (values 1 से 100 तक) बनाओ row-wise maximum values निकालो। column-wise minimum values निकालो।
A=np.random.randint(1,101,(10,10))

In [24]:
A

array([[42, 84, 43, 81, 95, 37, 82, 45, 87, 61],
       [ 2, 17, 58, 53, 99, 10, 44, 75, 84, 78],
       [66, 51, 64, 91, 96, 42, 38, 77, 53, 45],
       [48,  5, 90, 13, 19, 86, 37, 32, 75, 60],
       [13, 92, 13, 75, 71, 51, 10, 25, 51, 91],
       [ 5, 26, 85, 14, 46, 64, 14, 36, 24, 55],
       [13, 53, 29, 63, 10, 28, 72, 59, 65,  3],
       [62, 89, 95, 25, 46, 46, 28, 95, 23, 83],
       [64, 18, 84, 40, 73, 83, 13, 33, 84, 12],
       [67, 10, 86, 26,  9, 74, 54, 39, 43,  1]], dtype=int32)

In [25]:
r=A.max(axis=1)      #row wise min val

In [26]:
r

array([95, 99, 96, 90, 92, 85, 72, 95, 84, 86], dtype=int32)

In [27]:
c=A.min(axis=0)       #column wise max val

In [28]:
c

array([ 2,  5, 13, 13,  9, 10, 10, 25, 23,  1], dtype=int32)

In [29]:
# एक 1D array A = [3, 4, 3, 7, 5, 4, 9, 7, 2, 2] से: unique elements निकालो (ascending order में)। हर element कितनी बार आया है, उसकी frequency निकालो।
B=np.array([3, 4, 3, 7, 5, 4, 9, 7, 2, 2])

In [30]:
B

array([3, 4, 3, 7, 5, 4, 9, 7, 2, 2])

In [32]:
u,freq=np.unique(B,return_counts=True)  #हर element कितनी बार आया है, उसकी frequency निकालो।

In [33]:
u,freq

(array([2, 3, 4, 5, 7, 9]), array([2, 2, 2, 1, 2, 1]))

In [34]:
# एक 6x6 random integer matrix (1 से 50 तक) बनाओ। उसका border elements निकालो (यानि पहली row, आखिरी row, पहला column, आखिरी column)। 
# सिर्फ border elements का sum निकालो।
C=np.random.randint(1,51,(6,6))


In [35]:
C

array([[16, 40,  6, 37, 40, 27],
       [13, 25,  9, 10, 19,  5],
       [39, 17, 42, 49,  3, 14],
       [24,  1,  3, 46, 43, 31],
       [ 5, 17, 17, 17, 43, 27],
       [26, 42, 32, 26, 17, 37]], dtype=int32)

In [36]:
# उसका border elements निकालो (यानि पहली row, आखिरी row, पहला column, आखिरी column)। 

In [37]:
r1=C[0,:]
r2=C[-1,:]
c1=C[:,0]
c2=C[:,-1]

In [38]:
border=r1.sum()+r2.sum()+c1.sum()+c2.sum()-(C[0,0]+C[0,-1]+C[-1,0],C[-1,-1]) # सिर्फ border elements का sum निकालो।
border

array([541, 573])

In [39]:
# एक array बनाओ जिसमें values 0 से 19 तक हों।

# उसे 4x5 matrix में reshape करो।

# फिर उस matrix को row-wise reverse और column-wise reverse करके दिखाओ।

S=np.arange(0,20)

In [40]:
S

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [41]:
re=S.reshape(4,5)
re

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [47]:
row=np.flip(re,axis=1)
row

array([[ 4,  3,  2,  1,  0],
       [ 9,  8,  7,  6,  5],
       [14, 13, 12, 11, 10],
       [19, 18, 17, 16, 15]])

In [48]:
col=np.flip(re,axis=0)
col

array([[15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [ ]:
# Q7️⃣ (Revision + Hard)

# एक 7x7 matrix बनाओ जिसमें 1 से 49 तक numbers हों।

# main diagonal और secondary diagonal का sum निकालो।

# फिर diagonal elements को 0 से replace कर दो।
# Q8️⃣ (Tricky)

# एक 8x8 matrix बनाओ जिसमें random integers (10–99) हों।

# matrix में जितने भी even numbers हैं, उन्हें -1 से replace करो।

# फिर row-wise sum निकालो।
# Q9️⃣ (Combined)

# एक array D = [4,7,2,9,7,2,5,4,3,5]

# unique elements निकालो और frequency dictionary बनाओ।

# फिर एक नया array बनाओ जिसमें frequency > 1 वाले elements ही हो।

In [68]:
M=np.random.randint(1,50,(7,7))
M

array([[23, 20, 27, 42, 44, 26, 46],
       [26,  5, 30, 16, 30, 42, 18],
       [21, 14, 38, 10,  9, 11, 33],
       [42, 28, 40, 37, 10, 17, 16],
       [ 2,  5, 28, 21,  3, 22, 49],
       [47, 32, 24,  6, 43, 23, 27],
       [18,  1, 30,  5,  8, 23, 21]], dtype=int32)

In [69]:
main=np.diag(M)
main

array([23,  5, 38, 37,  3, 23, 21], dtype=int32)

In [70]:
cr=np.diag(np.fliplr(M))
cr

array([46, 42,  9, 37, 28, 32, 18], dtype=int32)

In [71]:
t=main.sum()+cr.sum()-M[3,3]
t

np.int64(325)

In [72]:
M[np.arange(7),np.arange(7)]=0
M[np.arange(7),np.arange(6,-1,-1)]=0
M

array([[ 0, 20, 27, 42, 44, 26,  0],
       [26,  0, 30, 16, 30,  0, 18],
       [21, 14,  0, 10,  0, 11, 33],
       [42, 28, 40,  0, 10, 17, 16],
       [ 2,  5,  0, 21,  0, 22, 49],
       [47,  0, 24,  6, 43,  0, 27],
       [ 0,  1, 30,  5,  8, 23,  0]], dtype=int32)

In [79]:
# Q8️⃣ (Tricky)

# एक 8x8 matrix बनाओ जिसमें random integers (10–99) हों।

# matrix में जितने भी even numbers हैं, उन्हें -1 से replace करो।

# फिर row-wise sum निकालो।

E=np.random.randint(10,100,(8,8))
E

array([[21, 87, 52, 23, 31, 53, 85, 64],
       [56, 19, 73, 49, 36, 22, 21, 79],
       [20, 89, 98, 54, 90, 58, 92, 51],
       [51, 26, 64, 17, 71, 30, 92, 42],
       [48, 46, 69, 85, 12, 96, 75, 17],
       [95, 39, 26, 10, 74, 34, 45, 61],
       [28, 59, 92, 87, 37, 59, 94, 77],
       [96, 16, 74, 32, 80, 16, 58, 71]], dtype=int32)

In [80]:

E[E%2==0]= -1
E

      

array([[21, 87, -1, 23, 31, 53, 85, -1],
       [-1, 19, 73, 49, -1, -1, 21, 79],
       [-1, 89, -1, -1, -1, -1, -1, 51],
       [51, -1, -1, 17, 71, -1, -1, -1],
       [-1, -1, 69, 85, -1, -1, 75, 17],
       [95, 39, -1, -1, -1, -1, 45, 61],
       [-1, 59, -1, 87, 37, 59, -1, 77],
       [-1, -1, -1, -1, -1, -1, -1, 71]], dtype=int32)

In [81]:
r=E.sum(axis=1)
r

array([298, 238, 134, 134, 242, 236, 316,  64])

In [ ]:
# Q9️⃣ (Combined)

# एक array D = [4,7,2,9,7,2,5,4,3,5]

# unique elements निकालो और frequency dictionary बनाओ।

# फिर एक नया array बनाओ जिसमें frequency > 1 वाले elements ही हो।

In [86]:
D=np.array([4,7,2,9,7,2,5,4,3,5])
D

array([4, 7, 2, 9, 7, 2, 5, 4, 3, 5])

In [87]:
u,fre=np.unique(D,return_counts=True)
u,fre

(array([2, 3, 4, 5, 7, 9]), array([2, 1, 2, 2, 2, 1]))

In [90]:
N=np.array([4,4,2,2,7,7,5,5,5])
N

array([4, 4, 2, 2, 7, 7, 5, 5, 5])

In [91]:
u,fre=np.unique(N,return_counts=True)
u,fre

(array([2, 4, 5, 7]), array([2, 2, 3, 2]))

In [128]:
# Q10️⃣ (Super Hard)
# एक 10x10 matrix बनाओ जिसमें random integers 1–100 हों।
# उस matrix में:
# prime numbers को -1 से replace करो।
# multiples of 5 को 0 से replace करो।
# फिर:
# row-wise और column-wise sum निकालो।
# matrix में जो values positive हैं, उनका total sum निकालो।
# 💡 Hint:
# Prime numbers check करने के लिए vectorized method use करो।
# Masking + fancy indexing + logical operations बहुत useful होंगे।

Z=np.random.randint(1,101,(10,10))
Z



array([[ 29,  80,  16,  42,  35,  81,  43,  98,   3,  58],
       [ 74,  93,  35,  84,  31,  87,  27,  83,  28,  76],
       [ 10,  25,  19,  35,  21,  11,  84,  24,  32,  47],
       [ 34,  15,  47,  29,  20,  18, 100,  23,  46,  97],
       [ 35,  91,  35,  92,  13,  73,  85,  49,  20,  19],
       [ 73,  32,  52,  23,  11,  39,  91,  17,  30,  33],
       [ 21,   5,  43,  89,  41,  60,  62,  47,  78,  79],
       [ 76,  28,  38,  54,  72,  64,  94,   7,   9,  19],
       [ 67,  35,  59,  69,  55,  51,  50,  73,  23,   5],
       [ 90,  61,  71,   1,  60,   2,  57,  70,  19,  77]], dtype=int32)

In [129]:
def is_prime(n):
    if n<2:
        return False
    for i in range(2,int(n**0.5)+1):
        if n%i==0:
            return False
    return True


pm=np.vectorize(is_prime)(Z)
Z[pm] = -1
      
        

In [130]:
Z[Z%5==0]=0
Z

array([[-1,  0, 16, 42,  0, 81, -1, 98, -1, 58],
       [74, 93,  0, 84, -1, 87, 27, -1, 28, 76],
       [ 0,  0, -1,  0, 21, -1, 84, 24, 32, -1],
       [34,  0, -1, -1,  0, 18,  0, -1, 46, -1],
       [ 0, 91,  0, 92, -1, -1,  0, 49,  0, -1],
       [-1, 32, 52, -1, -1, 39, 91, -1,  0, 33],
       [21, -1, -1, -1, -1,  0, 62, -1, 78, -1],
       [76, 28, 38, 54, 72, 64, 94, -1,  9, -1],
       [-1,  0, -1, 69,  0, 51,  0, -1, -1, -1],
       [ 0, -1, -1,  1,  0, -1, 57,  0, -1, 77]], dtype=int32)

In [133]:
r=Z.sum(axis=1)
r


array([292, 467, 158,  94, 229, 243, 155, 433, 115, 131])

In [134]:
c=Z.sum(axis=0)
c

array([202, 242, 101, 339,  89, 337, 414, 165, 190, 238])

In [135]:
p=Z[Z>0].sum()
p

np.int64(2353)

In [ ]:
# Q11️⃣ (Masking + Fancy Index + Condition)
# एक 12x12 matrix बनाओ जिसमें random integers 1–150 हों।
# Matrix में:
# जो numbers prime और odd दोनों हैं, उन्हें -1 से replace करो।
# जो numbers multiples of 7 हैं, उन्हें 0 से replace करो।
# फिर:
# row-wise maximum निकालो।
# column-wise minimum निकालो।

In [143]:
T=np.random.randint(1,151,(12,12))
T

array([[ 92, 114, 127,  29, 146,  31,  14,  81,  74,  45, 119,  95],
       [  3, 145,  31,  17,  19,  83,  46,  49,  67, 100,  91, 126],
       [ 97,   1,  51, 118,  46,  73,  43,  28,  74,  31, 120,  49],
       [137, 108, 110, 111,  71,  93, 146, 150,  59,  17,  22,  77],
       [  4, 124,  83,  97, 126,  11,  10,  89,  47, 123,  46,   9],
       [ 52,  61,  40, 132,  88,  51, 112,   2,  27,   9,  67,  51],
       [116, 118,   3,  43,  80,  85,   7,  11, 135,  13, 148, 147],
       [104,  12, 101,  82, 144, 133, 124,  57, 136, 143,  52,  96],
       [ 66,  18,  45,  53,  75,  14,  65,  31,  42,  16, 115, 142],
       [  1,  27,  88,  96,   6,   1,  90,  30,  48,  53,  22, 132],
       [141, 129,  99, 147,  76,  69, 140,  32,  53, 147, 139, 135],
       [ 77,  70,  29,  59,  99,  13,  31,  51, 113, 110,  65,  96]],
      dtype=int32)

In [144]:
def is_prime(n):
    if n<2:
        return False
    for i in range(2, int(n**0.5)+1):
        if n%i==0:
            return False
    return True


pm=np.vectorize(is_prime)(T)
odd=(T%2!=0)
T[pm]= -1
mask=pm+odd
T[mask]=-1

In [145]:
T[T%7==0]=0
T

array([[ 92, 114,  -1,  -1, 146,  -1,   0,  -1,  74,  -1,  -1,  -1],
       [ -1,  -1,  -1,  -1,  -1,  -1,  46,  -1,  -1, 100,  -1,   0],
       [ -1,  -1,  -1, 118,  46,  -1,  -1,   0,  74,  -1, 120,  -1],
       [ -1, 108, 110,  -1,  -1,  -1, 146, 150,  -1,  -1,  22,  -1],
       [  4, 124,  -1,  -1,   0,  -1,  10,  -1,  -1,  -1,  46,  -1],
       [ 52,  -1,  40, 132,  88,  -1,   0,  -1,  -1,  -1,  -1,  -1],
       [116, 118,  -1,  -1,  80,  -1,  -1,  -1,  -1,  -1, 148,  -1],
       [104,  12,  -1,  82, 144,  -1, 124,  -1, 136,  -1,  52,  96],
       [ 66,  18,  -1,  -1,  -1,   0,  -1,  -1,   0,  16,  -1, 142],
       [ -1,  -1,  88,  96,   6,  -1,  90,  30,  48,  -1,  22, 132],
       [ -1,  -1,  -1,  -1,  76,  -1,   0,  32,  -1,  -1,  -1,  -1],
       [ -1,   0,  -1,  -1,  -1,  -1,  -1,  -1,  -1, 110,  -1,  96]],
      dtype=int32)

In [146]:
r=T.max(axis=1)
r

array([146, 100, 120, 150, 124, 132, 148, 144, 142, 132,  76, 110],
      dtype=int32)

In [147]:
c=T.min(axis=0)
c

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1], dtype=int32)

In [213]:
# Q12️⃣ (Diagonal + Sum + Condition)
# एक 9x9 matrix बनाओ जिसमें 1–81 तक numbers हों।
# Main और secondary diagonals का sum निकालो।
# Diagonal में जितने भी even numbers हैं, उन्हें -2 से replace करो।
# फिर matrix का total sum निकालो।

In [214]:
R=np.arange(1,82).reshape(9,9)
R

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60, 61, 62, 63],
       [64, 65, 66, 67, 68, 69, 70, 71, 72],
       [73, 74, 75, 76, 77, 78, 79, 80, 81]])

In [215]:
main=np.diag(R)
main


array([ 1, 11, 21, 31, 41, 51, 61, 71, 81])

In [216]:
sec=np.diag(np.fliplr(R))
sec

array([ 9, 17, 25, 33, 41, 49, 57, 65, 73])

In [218]:
total = main.sum() + sec.sum()
total

np.int64(738)

In [219]:
for i in range(9):
    if R[i, i] % 2 == 0:       # main diagonal
        R[i, i] = -2
    if R[i, 8 - i] % 2 == 0:   # secondary diagonal
        R[i, 8 - i] = -2

In [222]:
R

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60, 61, 62, 63],
       [64, 65, 66, 67, 68, 69, 70, 71, 72],
       [73, 74, 75, 76, 77, 78, 79, 80, 81]])

In [223]:
matrix_sum=R.sum()
matrix_sum

np.int64(3321)