In [ ]:
एक 1D NumPy array बनाओ जिसमें 1 से 10 तक के numbers हों।

एक 3x3 का array बनाओ जिसमें सारे elements 0 हों।

एक random 4x4 matrix बनाओ और उसका transpose निकालो।

एक array बनाओ [10,20,30,40,50] और उसका mean, max और min निकालो।

एक 2D array (3x3) बनाओ और उसकी 2nd row print करो।

In [3]:
import numpy as np

In [5]:
# एक 1D NumPy array बनाओ जिसमें 1 से 10 तक के numbers हों।

np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
# एक 3x3 का array बनाओ जिसमें सारे elements 0 हों।

np.zeros([3,3])


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
# एक random 4x4 matrix बनाओ और उसका transpose निकालो।

import random
s=np.random.randint(1,5,(4,4))
s

array([[1, 3, 3, 3],
       [4, 3, 2, 1],
       [4, 3, 4, 1],
       [4, 2, 2, 4]], dtype=int32)

In [17]:
s.T

array([[1, 4, 4, 4],
       [3, 3, 3, 2],
       [3, 2, 4, 2],
       [3, 1, 1, 4]], dtype=int32)

In [22]:
# एक array बनाओ [10,20,30,40,50] और उसका mean, max और min निकालो।

a=np.array([10,20,30,40,50]).max()

In [23]:
a

np.int64(50)

In [24]:
a=np.array([10,20,30,40,50]).mean()

In [25]:
a

np.float64(30.0)

In [26]:
a=np.array([10,20,30,40,50]).min()

In [27]:
a

np.int64(10)

In [29]:
# एक 2D array (3x3) बनाओ और उसकी 2nd row print करो।

ar=np.random.randint(1,4,(3,3))

In [30]:
ar

array([[1, 3, 2],
       [1, 1, 2],
       [2, 2, 1]], dtype=int32)

In [32]:
ar[1]

array([1, 1, 2], dtype=int32)

In [ ]:
एक 5x5 random matrix बनाओ और उसमें से diagonal elements निकालो।

एक 1D array [1,2,3,4,5,6,7,8,9] लो → इसे 3x3 matrix में reshape करो।

दो random arrays (size 5x5) बनाओ और उनका matrix multiplication करो।

एक 10x10 random matrix बनाओ और उसका row-wise और column-wise sum निकालो।

एक array बनाओ [3,6,9,12,15,18,21] और check करो कौन से elements 5 से divisible हैं।

In [72]:
# एक 5x5 random matrix बनाओ और उसमें से diagonal elements निकालो।

a=np.random.randint(1,6,(5,5))
a

array([[4, 5, 5, 3, 4],
       [4, 4, 4, 4, 5],
       [4, 1, 4, 2, 5],
       [5, 1, 2, 3, 3],
       [4, 4, 1, 5, 3]], dtype=int32)

In [75]:
np.diag(a)


array([4, 4, 4, 3, 3], dtype=int32)

In [49]:
# एक 1D array [1,2,3,4,5,6,7,8,9] लो → इसे 3x3 matrix में reshape करो।

z=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)

In [50]:
z

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
# दो random arrays (size 5x5) बनाओ और उनका matrix multiplication करो।

A=np.random.randint(1,6,(5,5))
B=np.random.randint(1,6,(5,5))


In [53]:
A

array([[1, 1, 2, 3, 3],
       [5, 1, 1, 5, 1],
       [3, 5, 3, 2, 1],
       [4, 1, 4, 5, 1],
       [2, 4, 1, 4, 2]], dtype=int32)

In [54]:
B

array([[2, 4, 1, 5, 5],
       [1, 3, 5, 5, 1],
       [4, 1, 4, 3, 5],
       [3, 2, 4, 5, 1],
       [2, 4, 5, 2, 4]], dtype=int32)

In [55]:
A@B

array([[26, 27, 41, 37, 31],
       [32, 38, 39, 60, 40],
       [31, 38, 53, 61, 41],
       [42, 37, 50, 64, 50],
       [28, 37, 52, 57, 31]], dtype=int32)

In [56]:
# एक 10x10 random matrix बनाओ और उसका row-wise और column-wise sum निकालो।

A=np.random.randint(1,6,(10,10))
B=np.random.randint(1,6,(10,10))


In [57]:
A

array([[2, 5, 1, 2, 2, 3, 4, 2, 2, 3],
       [3, 3, 3, 2, 2, 4, 2, 3, 1, 3],
       [3, 5, 5, 2, 5, 1, 4, 5, 4, 4],
       [4, 2, 4, 2, 3, 5, 1, 2, 4, 3],
       [3, 3, 3, 3, 2, 5, 2, 3, 5, 5],
       [2, 3, 1, 3, 3, 1, 4, 2, 2, 4],
       [1, 5, 4, 2, 5, 2, 2, 1, 5, 5],
       [2, 3, 5, 5, 2, 5, 3, 5, 3, 3],
       [3, 1, 3, 1, 3, 1, 4, 2, 4, 1],
       [4, 1, 5, 3, 5, 3, 1, 5, 2, 1]], dtype=int32)

In [58]:
B

array([[5, 3, 4, 3, 2, 3, 2, 3, 4, 5],
       [4, 5, 3, 3, 3, 3, 3, 3, 3, 5],
       [5, 1, 3, 4, 1, 2, 2, 1, 3, 2],
       [2, 3, 5, 2, 1, 2, 2, 5, 1, 1],
       [5, 1, 4, 3, 3, 3, 5, 2, 1, 5],
       [2, 2, 3, 5, 5, 1, 1, 5, 2, 5],
       [2, 3, 5, 5, 5, 2, 2, 1, 4, 1],
       [4, 4, 3, 1, 5, 4, 2, 5, 3, 3],
       [4, 5, 5, 3, 3, 2, 5, 1, 1, 5],
       [1, 1, 2, 3, 2, 3, 5, 2, 3, 5]], dtype=int32)

In [59]:
A+B

array([[ 7,  8,  5,  5,  4,  6,  6,  5,  6,  8],
       [ 7,  8,  6,  5,  5,  7,  5,  6,  4,  8],
       [ 8,  6,  8,  6,  6,  3,  6,  6,  7,  6],
       [ 6,  5,  9,  4,  4,  7,  3,  7,  5,  4],
       [ 8,  4,  7,  6,  5,  8,  7,  5,  6, 10],
       [ 4,  5,  4,  8,  8,  2,  5,  7,  4,  9],
       [ 3,  8,  9,  7, 10,  4,  4,  2,  9,  6],
       [ 6,  7,  8,  6,  7,  9,  5, 10,  6,  6],
       [ 7,  6,  8,  4,  6,  3,  9,  3,  5,  6],
       [ 5,  2,  7,  6,  7,  6,  6,  7,  5,  6]], dtype=int32)

In [2]:
import numpy as np
A=np.random.randint(1,6,(10,10))
A

array([[3, 2, 3, 4, 3, 5, 5, 1, 5, 4],
       [2, 3, 3, 5, 4, 1, 3, 5, 4, 4],
       [4, 2, 2, 3, 3, 3, 4, 4, 1, 2],
       [3, 5, 3, 4, 1, 4, 5, 4, 4, 4],
       [5, 5, 4, 5, 4, 2, 1, 1, 4, 3],
       [3, 2, 4, 1, 4, 3, 3, 4, 5, 4],
       [4, 5, 1, 1, 2, 1, 3, 2, 3, 5],
       [5, 4, 4, 3, 1, 3, 5, 3, 4, 5],
       [1, 4, 1, 4, 5, 3, 5, 4, 3, 5],
       [4, 5, 2, 4, 5, 3, 4, 5, 4, 2]], dtype=int32)

In [4]:
r=A.sum(axis=1)  #ROW=1
r

array([35, 34, 28, 37, 34, 33, 27, 37, 35, 38])

In [5]:
c=A.sum(axis=0)  #COL=0
c

array([34, 37, 27, 34, 32, 28, 38, 33, 37, 38])

In [80]:
import numpy as np

A = np.random.randint(1,6,(10,10))
print("Matrix:\n", A)

# Row-wise sum
row_sum = A.sum(axis=1)
print("\nRow-wise sum:\n", row_sum)

# Column-wise sum
col_sum = A.sum(axis=0)
print("\nColumn-wise sum:\n", col_sum)


Matrix:
 [[4 4 3 5 3 5 1 1 3 5]
 [4 5 1 3 5 5 5 2 2 3]
 [4 1 3 4 5 2 5 2 2 4]
 [3 3 5 3 3 2 3 4 3 5]
 [2 5 1 4 2 1 3 3 3 2]
 [3 2 5 1 1 4 3 3 4 2]
 [5 2 3 4 1 1 5 3 5 3]
 [2 1 1 2 2 3 1 5 3 4]
 [4 4 5 5 3 4 2 5 1 5]
 [5 5 5 4 4 3 3 1 3 2]]

Row-wise sum:
 [34 35 32 34 26 28 32 24 38 35]

Column-wise sum:
 [36 32 32 35 29 30 31 29 29 35]


In [70]:
# एक array बनाओ [3,6,9,12,15,18,21] और check करो कौन से elements 5 से divisible हैं।

a=np.array([3,6,9,12,15,18,21])
for i in a:
    if i%5==0:
        print(i)    
    

15


In [7]:
# एक 10x10 random matrix (1 से 100 के बीच) बनाओ और उसमे से maximum element और उसका index (row, column position) निकालो।

A = np.random.randint(1,101,(10,10))
A


array([[ 4,  2, 26, 81, 19, 80,  5, 94, 22, 15],
       [ 1,  3, 50, 35, 77, 85, 25, 24, 87, 88],
       [82, 65, 87, 11, 23, 32, 50, 13, 57, 26],
       [39, 54, 94, 30, 40, 11, 51, 93, 93, 93],
       [35, 51, 84, 46, 31, 95, 52, 28,  5, 33],
       [70, 19, 25, 91, 82, 10, 26, 23, 13, 71],
       [27, 88, 46, 78, 19,  9, 62, 96, 57, 43],
       [63, 98, 16, 51, 22, 60, 83, 31, 94, 59],
       [42, 30, 17, 40, 37, 54, 25, 96, 75, 99],
       [98, 64, 85, 84, 64, 41, 72, 60, 72, 32]], dtype=int32)

In [8]:
maxi=A.max()

In [9]:
maxi

np.int32(99)

In [10]:
pos=np.argmax(A)
pos

np.int64(89)

In [12]:
p=np.unravel_index(pos,A.shape)
p

(np.int64(8), np.int64(9))

In [21]:
# एक array बनाओ 1 से 50 तक और check करो कौन से numbers prime हैं। Output में सिर्फ prime numbers वाला array आना चाहिए।
import numpy as np
A = np.arange(1,51)
A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [22]:
def is_prime(n):
    if n<2:
        return False
    for i in range(2, int(np.sqrt(n))+1):
        if n%i==0:
            return False
    return True

prime_numbers = A[[is_prime(x) for x in A]]
print(prime_numbers)


[ 2  3  5  7 11 13 17 19 23 29 31 37 41 43 47]


In [27]:
# एक 5x5 random matrix बनाओ और उसकी diagonal elements का sum निकालो (main diagonal और anti-diagonal दोनों)।

A=np.random.randint(1,10,(5,5))
A



array([[5, 2, 2, 9, 5],
       [1, 5, 9, 5, 2],
       [5, 5, 8, 9, 7],
       [6, 1, 6, 3, 2],
       [3, 3, 8, 5, 6]], dtype=int32)

In [30]:
d=np.diag(A).sum()
d

np.int64(27)

In [31]:
anti_diag_sum = np.diag(np.fliplr(A)).sum()
anti_diag_sum

np.int64(22)

In [37]:
# एक array बनाओ [2,4,6,8,10,12,14,16,18,20] और उसमें से वो elements निकालो जो 4 और 6 दोनों से divisible हों।

a=np.array([2,4,6,8,10,12,14,16,18,20])
for i in a:
    if i%4==0 and i%6==0:
        print(i)

12


In [45]:
# एक random array (size 15, values 1 से 30 तक) बनाओ और उसमें से unique elements print करो (duplicates remove करके)।

A=np.random.randint(1,31,(5,3))

In [46]:
A

array([[23, 30, 23],
       [14, 15,  4],
       [18,  5, 19],
       [ 5,  3,  7],
       [11,  3,  7]], dtype=int32)

In [47]:
u=np.unique(A)

In [48]:
u

array([ 3,  4,  5,  7, 11, 14, 15, 18, 19, 23, 30], dtype=int32)

In [49]:
u, idx = np.unique(A, return_index=True)
u = u[np.argsort(idx)]
print(u)


[23 30 14 15  4 18  5 19  3  7 11]
