In [1]:
import numpy as np

In [9]:
arr= np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [10]:
arr[5,4]

np.int64(30)

In [13]:
s=arr[3:5,2:4]
s

array([[18, 19],
       [23, 24]])

In [15]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [16]:
arr[4]#row

array([21, 22, 23, 24, 25])

In [17]:
arr[:,3]#col

array([ 4,  9, 14, 19, 24, 29])

In [52]:
a=np.arange(1,21)#deep copy
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [53]:
a[3:9]

array([4, 5, 6, 7, 8, 9])

In [54]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [71]:
a=np.arange(1,21)#shallow copy
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [72]:
a=a[3:9]


In [73]:
a

array([4, 5, 6, 7, 8, 9])

In [74]:
a

array([4, 5, 6, 7, 8, 9])

In [75]:
b=a.copy()

In [76]:
b

array([4, 5, 6, 7, 8, 9])

In [77]:
b[0]=99

In [78]:
b

array([99,  5,  6,  7,  8,  9])

In [79]:
a

array([4, 5, 6, 7, 8, 9])

In [87]:
#matrix operation

A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
A


array([[1, 2],
       [3, 4]])

In [88]:
B

array([[5, 6],
       [7, 8]])

In [89]:
A@B

array([[19, 22],
       [43, 50]])

**PW**

In [105]:
arr=np.random.randint(1,5,(5,4))

In [106]:
arr

array([[3, 3, 3, 3],
       [3, 2, 2, 3],
       [4, 2, 1, 4],
       [4, 2, 3, 3],
       [3, 4, 3, 1]], dtype=int32)

In [114]:
arr[4,3]

np.int32(1)

In [118]:
arr[:3]

array([[3, 3, 3, 3],
       [3, 2, 2, 3],
       [4, 2, 1, 4]], dtype=int32)

In [119]:
arr[:3,:3]

array([[3, 3, 3],
       [3, 2, 2],
       [4, 2, 1]], dtype=int32)

In [ ]:
# Math OPERATIONS

In [125]:
A=np.random.randint(1,3,(3,3))
B=np.random.randint(1,3,(3,3))

In [126]:
A

array([[2, 2, 2],
       [1, 1, 2],
       [1, 2, 2]], dtype=int32)

In [127]:
B

array([[2, 2, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [128]:
A@B

array([[8, 8, 6],
       [5, 5, 4],
       [6, 6, 5]], dtype=int32)